=== stefanmerk/swa/shop/src/test/resources/datasets/db.dtd
<!ELEMENT dataset (
    KUNDE*,
    ADRESSE*,
    ARTIKEL*,
    BESTELLUNG*,
    BESTELLPOSITION*)>

<!ELEMENT KUNDE EMPTY>
<!ATTLIST KUNDE
    K_ID CDATA #REQUIRED
    NACHNAME CDATA #REQUIRED
    VORNAME CDATA #IMPLIED
    GESCHLECHT CDATA #IMPLIED
    EMAIL CDATA #REQUIRED
    PASSWORD CDATA #IMPLIED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT ADRESSE EMPTY>
<!ATTLIST ADRESSE
    A_ID CDATA #REQUIRED
    PLZ CDATA #REQUIRED
    ORT CDATA #REQUIRED
    STRASSE CDATA #IMPLIED
    HAUSNR CDATA #IMPLIED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
    KUNDE_FK CDATA #REQUIRED
>

<!ELEMENT ARTIKEL EMPTY>
<!ATTLIST ARTIKEL
    A_ID CDATA #REQUIRED
    BEZEICHNUNG CDATA #REQUIRED
    PREIS CDATA #IMPLIED
    VERFUEGBARKEIT CDATA #IMPLIED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT BESTELLUNG EMPTY>
<!ATTLIST BESTELLUNG
    B_ID CDATA #REQUIRED
    KUNDE_FK CDATA #REQUIRED
    IDX CDATA #IMPLIED
    ERZEUGT CDATA #REQUIRED
    AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT BESTELLPOSITION EMPTY>
<!ATTLIST BESTELLPOSITION
    BP_ID CDATA #REQUIRED
    BESTELLUNG_FK CDATA #REQUIRED
    ARTIKEL_FK CDATA #REQUIRED
    ANZAHL CDATA #REQUIRED
    IDX CDATA #IMPLIED
>

=== stefanmerk/swa/shop/src/test/resources/datasets/db.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE dataset SYSTEM "db.dtd">
<dataset>
  <KUNDE K_ID="100" NACHNAME="Mustermann" VORNAME="Max" GESCHLECHT="m" EMAIL="max@hska.de" PASSWORD="100" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <KUNDE K_ID="101" NACHNAME="Schmidt" VORNAME="Anna" GESCHLECHT="w" EMAIL="anna@hska.de" PASSWORD="101" ERZEUGT="2006-08-01 01:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <KUNDE K_ID="102" NACHNAME="Donald" VORNAME="Duck" GESCHLECHT="m" EMAIL="donald@hska.de" PASSWORD="102" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 10:00:00.0"/>
  <KUNDE K_ID="103" NACHNAME="Sponge" VORNAME="Bob" GESCHLECHT="m" EMAIL="sponge@hska.de" PASSWORD="103" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <KUNDE K_ID="104" NACHNAME="Gart" VORNAME="Hilde" GESCHLECHT="w" EMAIL="hilde@hska.de" PASSWORD="104" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 10:00:00.0"/>
  <ADRESSE A_ID="200" PLZ="89233" ORT="Ulm" STRASSE="Hirschstraße" HAUSNR="12" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0" KUNDE_FK="100"/>
  <ADRESSE A_ID="201" PLZ="76133" ORT="Karlsruhe" STRASSE="Kronenplatz" HAUSNR="5" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 10:00:00.0" KUNDE_FK="102"/>
  <ADRESSE A_ID="202" PLZ="10717" ORT="Berlin" STRASSE="Uhlandstraße" HAUSNR="109" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0" KUNDE_FK="103"/>
  <ADRESSE A_ID="203" PLZ="76437" ORT="Rastatt" STRASSE="Oberwald" HAUSNR="4" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0" KUNDE_FK="104"/>
  <ADRESSE A_ID="204" PLZ="73733" ORT="Esslingen" STRASSE="Obertorstraße" HAUSNR="60" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0" KUNDE_FK="101"/>
  <ARTIKEL A_ID="300" BEZEICHNUNG="Hose-Diesel" PREIS="139.0" VERFUEGBARKEIT="y" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <ARTIKEL A_ID="301" BEZEICHNUNG="T-Shirt-G-STAR" PREIS="19.0" VERFUEGBARKEIT="y" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <ARTIKEL A_ID="302" BEZEICHNUNG="Uhr-Fossil" PREIS="198.0" VERFUEGBARKEIT="y" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <ARTIKEL A_ID="303" BEZEICHNUNG="Tasche-GUESS" PREIS="150.0" VERFUEGBARKEIT="y" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 10:00:00.0"/>
  <ARTIKEL A_ID="304" BEZEICHNUNG="Rock-Maison Scotch" PREIS="60.0" VERFUEGBARKEIT="y" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <ARTIKEL A_ID="305" BEZEICHNUNG="Sneakers-G-UNIT" PREIS="99.0" VERFUEGBARKEIT="y" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <ARTIKEL A_ID="306" BEZEICHNUNG="Brille-Ray Ban" PREIS="120.0" VERFUEGBARKEIT="y" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <BESTELLUNG B_ID="400" KUNDE_FK="100" IDX="0" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <BESTELLUNG B_ID="401" KUNDE_FK="100" IDX="1" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <BESTELLUNG B_ID="402" KUNDE_FK="101" IDX="0" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <BESTELLUNG B_ID="403" KUNDE_FK="101" IDX="1" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <BESTELLUNG B_ID="404" KUNDE_FK="103" IDX="0" ERZEUGT="2006-08-01 10:00:00.0" AKTUALISIERT="2006-08-01 01:00:00.0"/>
  <BESTELLPOSITION BP_ID="500" BESTELLUNG_FK="400" ARTIKEL_FK="300" ANZAHL="1" IDX="0"/>
  <BESTELLPOSITION BP_ID="501" BESTELLUNG_FK="400" ARTIKEL_FK="301" ANZAHL="4" IDX="1"/>
  <BESTELLPOSITION BP_ID="502" BESTELLUNG_FK="401" ARTIKEL_FK="302" ANZAHL="5" IDX="0"/>
  <BESTELLPOSITION BP_ID="503" BESTELLUNG_FK="402" ARTIKEL_FK="303" ANZAHL="3" IDX="0"/>
  <BESTELLPOSITION BP_ID="504" BESTELLUNG_FK="402" ARTIKEL_FK="304" ANZAHL="2" IDX="1"/>
  <BESTELLPOSITION BP_ID="505" BESTELLUNG_FK="403" ARTIKEL_FK="305" ANZAHL="1" IDX="0"/>
  <BESTELLPOSITION BP_ID="506" BESTELLUNG_FK="404" ARTIKEL_FK="300" ANZAHL="5" IDX="0"/>
  <BESTELLPOSITION BP_ID="507" BESTELLUNG_FK="404" ARTIKEL_FK="301" ANZAHL="2" IDX="1"/>
  <BESTELLPOSITION BP_ID="508" BESTELLUNG_FK="404" ARTIKEL_FK="302" ANZAHL="8" IDX="2"/>
</dataset>
